"use client";

import { useState } from "react";
import Link from "next/link";
import {
  ArrowRight, CalendarCheck, CheckCircle2, ClipboardList, Globe, GraduationCap,
  Menu, Moon, Package, ShieldCheck, Stethoscope, Sun, UserCog, X, Bot,
  Activity, FileCheck2, LockKeyhole, MessageCircle, ChevronRight,
} from "lucide-react";

type Lang = "en" | "ms";

const content = {
  en: {
    nav: ["Everything Connected", "Precision for every user", "Support at every step", "Protected by Design"],
    access: "Access system", motto: "Kewajipan. Maruah. Integriti",
    heroEyebrow: "UPNM Health Centre", heroTitle: "Campus healthcare, made clear.",
    heroText: "UPNM Clinical Management System brings appointments, medical records, pharmacy and follow-up care into one trusted place.",
    primary: "Access clinical system", secondary: "Explore services", official: "Official campus health service",
    connectedTitle: "One patient. One connected journey.", connectedText: "Every step of care stays connected, from the first appointment request to the medical record and pharmacy counter.",
    connected: [["01", "Request", "Start an appointment or health request."], ["02", "Consult", "A medical officer reviews your care."], ["03", "Dispense", "Receive a clear prescription and follow-up."], ["04", "Record", "Keep a protected history for future care."]],
    precisionTitle: "Precision for every user.", precisionText: "Clear tools for the people who keep campus healthcare moving.",
    roles: [["Students & lecturers", "Book visits, view prescriptions and manage your personal health portal.", GraduationCap], ["Medical officers", "Review the clinical queue, complete notes and support patient care.", Stethoscope], ["Administrators", "Coordinate clinic operations, inventory and doctor availability.", UserCog]],
    supportTitle: "Support at every step.", supportText: "Practical clinical intelligence helps teams see what matters without making the experience complicated.",
    support: [["Clinical insights", "Relevant history is easier to find when a consultation begins.", Activity], ["Clinical alerts", "Important lab and vital-sign changes are made visible for review.", MessageCircle], ["Real-time queue", "Patient flow stays coordinated across the clinic.", CalendarCheck]],
    protectedTitle: "Protected by Design.", protectedText: "Sensitive clinical information deserves clear controls, responsible access and an accountable record of every action.",
    protected: [["Role-based access", "The right information for the right role.", LockKeyhole], ["Protected records", "Clinical information remains private and purposeful.", FileCheck2], ["Activity history", "Important actions remain visible for accountability.", ClipboardList]],
    servicesTitle: "Support for every stage of care", servicesText: "A straightforward digital front door for campus healthcare.",
    services: [["Appointments", "Request a consultation and view upcoming visits.", CalendarCheck], ["Medical records", "Keep consultations, certificates and health information together.", ClipboardList], ["Pharmacy", "Manage prescriptions and support safe dispensing.", Package]],
    botGreeting: "How can I help you?", botText: "I can help you find a service or start an appointment.", botButton: "Open MediBot", footer: "UPNM Health Centre · Kem Sungai Besi",
  },
  ms: {
    nav: ["Semuanya Terhubung", "Ketepatan untuk setiap pengguna", "Sokongan di setiap langkah", "Dilindungi oleh Reka Bentuk"],
    access: "Akses sistem", motto: "Kewajipan. Maruah. Integriti",
    heroEyebrow: "Pusat Kesihatan UPNM", heroTitle: "Penjagaan kesihatan kampus yang jelas.",
    heroText: "Sistem Pengurusan Klinikal UPNM menghimpunkan temu janji, rekod perubatan, farmasi dan penjagaan susulan di satu tempat.",
    primary: "Akses sistem klinikal", secondary: "Teroka perkhidmatan", official: "Perkhidmatan kesihatan kampus rasmi",
    connectedTitle: "Satu pesakit. Satu perjalanan terhubung.", connectedText: "Setiap langkah penjagaan kekal terhubung, daripada permintaan temu janji hingga rekod perubatan dan farmasi.",
    connected: [["01", "Mohon", "Mulakan temu janji atau permintaan kesihatan."], ["02", "Konsultasi", "Pegawai perubatan menyemak penjagaan anda."], ["03", "Dispens", "Terima preskripsi dan penjagaan susulan."], ["04", "Rekod", "Simpan sejarah yang dilindungi untuk penjagaan akan datang."]],
    precisionTitle: "Ketepatan untuk setiap pengguna.", precisionText: "Alat yang jelas untuk komuniti yang menggerakkan penjagaan kesihatan kampus.",
    roles: [["Pelajar & pensyarah", "Tempah lawatan, lihat preskripsi dan urus portal kesihatan peribadi.", GraduationCap], ["Pegawai perubatan", "Semak barisan klinikal, lengkapkan nota dan sokong penjagaan pesakit.", Stethoscope], ["Pentadbir", "Selaras operasi klinik, inventori dan ketersediaan doktor.", UserCog]],
    supportTitle: "Sokongan di setiap langkah.", supportText: "Kepintaran klinikal yang praktikal membantu pasukan melihat perkara penting tanpa menjadikan pengalaman rumit.",
    support: [["Cerapan klinikal", "Sejarah yang berkaitan lebih mudah dicari apabila konsultasi bermula.", Activity], ["Amaran klinikal", "Perubahan keputusan makmal dan tanda vital penting dipaparkan untuk semakan.", MessageCircle], ["Barisan masa nyata", "Aliran pesakit kekal terselaras di seluruh klinik.", CalendarCheck]],
    protectedTitle: "Dilindungi oleh Reka Bentuk.", protectedText: "Maklumat klinikal sensitif memerlukan kawalan jelas, akses bertanggungjawab dan rekod tindakan yang telus.",
    protected: [["Akses berasaskan peranan", "Maklumat yang tepat untuk setiap peranan.", LockKeyhole], ["Rekod terlindung", "Maklumat klinikal kekal peribadi dan bertujuan.", FileCheck2], ["Sejarah aktiviti", "Tindakan penting kekal kelihatan untuk akauntabiliti.", ClipboardList]],
    servicesTitle: "Sokongan untuk setiap peringkat penjagaan", servicesText: "Pintu masuk digital yang mudah untuk penjagaan kesihatan kampus.",
    services: [["Temu janji", "Mohon konsultasi dan lihat lawatan akan datang.", CalendarCheck], ["Rekod perubatan", "Simpan konsultasi dan maklumat kesihatan bersama.", ClipboardList], ["Farmasi", "Urus preskripsi dan sokong pendispensan yang selamat.", Package]],
    botGreeting: "Bagaimana saya boleh membantu?", botText: "Saya boleh membantu mencari perkhidmatan atau memulakan temu janji.", botButton: "Buka MediBot", footer: "Pusat Kesihatan UPNM · Kem Sungai Besi",
  },
} as const;

export default function LandingPage() {
  const [lang, setLang] = useState<Lang>("en");
  const [dark, setDark] = useState(false);
  const [mobileOpen, setMobileOpen] = useState(false);
  const [botOpen, setBotOpen] = useState(false);
  const t = content[lang];
  const targets = ["ecosystem", "roles", "intelligence", "security"];

  function scrollTo(id: string) { setMobileOpen(false); document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); }
  function toggleTheme() { setDark((value) => { const next = !value; document.documentElement.classList.toggle("dark", next); localStorage.setItem("theme", next ? "dark" : "light"); return next; }); }

  return <main className="min-h-screen bg-[#f6f7f5] text-[#183b35] dark:bg-[#10221d] dark:text-white">
    <header className="sticky top-0 z-50 border-b border-[#d9e1dc] bg-white/95 backdrop-blur dark:border-white/10 dark:bg-[#10221d]/95"><div className="mx-auto flex h-[76px] max-w-7xl items-center justify-between px-5 lg:px-10">
      <Link href="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center bg-[#183b35] text-white"><ShieldCheck className="h-5 w-5" /></span><span><span className="block text-[10px] font-bold uppercase tracking-[0.22em] text-[#718078]">UPNM</span><span className="block font-[Poppins] text-sm font-extrabold">Health Centre</span></span></Link>
      <nav className="hidden items-center gap-7 lg:flex">{t.nav.map((item, i) => <button key={item} onClick={() => scrollTo(targets[i])} className="text-xs font-semibold text-[#53655e] transition hover:text-[#183b35] dark:text-[#bdcbc4] dark:hover:text-white">{item}</button>)}</nav>
      <div className="hidden items-center gap-2 md:flex"><button onClick={() => setLang(lang === "en" ? "ms" : "en")} className="flex h-9 items-center gap-2 border border-[#d9e1dc] px-3 text-xs font-bold text-[#53655e] dark:border-white/15 dark:text-[#bdcbc4]"><Globe className="h-3.5 w-3.5" />{lang === "en" ? "BM" : "EN"}</button><button onClick={toggleTheme} className="grid h-9 w-9 place-items-center border border-[#d9e1dc] text-[#53655e] dark:border-white/15 dark:text-[#bdcbc4]" aria-label="Toggle theme">{dark ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}</button><Link href="/login" className="ml-2 bg-[#183b35] px-5 py-2.5 text-xs font-bold uppercase tracking-wide text-white transition hover:bg-[#2d5a50]">{t.access}</Link></div>
      <button className="grid h-10 w-10 place-items-center border border-[#d9e1dc] md:hidden dark:border-white/15" onClick={() => setMobileOpen(!mobileOpen)} aria-label="Toggle navigation">{mobileOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</button>
    </div>{mobileOpen && <div className="border-t border-[#d9e1dc] bg-white px-5 py-4 dark:border-white/10 dark:bg-[#10221d] md:hidden">{t.nav.map((item, i) => <button key={item} onClick={() => scrollTo(targets[i])} className="block w-full px-2 py-3 text-left text-sm text-[#53655e] dark:text-[#bdcbc4]">{item}</button>)}<Link href="/login" className="mt-2 block bg-[#183b35] px-4 py-3 text-center text-xs font-bold uppercase tracking-wide text-white">{t.access}</Link></div>}</header>

    <section className="border-b border-[#d9e1dc] bg-[#e9f0eb] dark:border-white/10 dark:bg-[#18352e]"><div className="mx-auto grid min-h-[600px] max-w-7xl items-center gap-14 px-5 py-20 lg:grid-cols-[1.05fr_0.95fr] lg:px-10 lg:py-24"><div className="max-w-2xl"><div className="mb-5 flex items-center gap-3 text-xs font-bold uppercase tracking-[0.18em] text-[#56796c]"><span className="h-2 w-2 rounded-full bg-[#e0aa25]" />{t.heroEyebrow}</div><div className="mb-7 text-xs font-bold uppercase tracking-[0.28em] text-[#718078]">{t.motto}</div><h1 className="max-w-xl font-[Poppins] text-5xl font-extrabold leading-[1.08] tracking-tight text-[#183b35] dark:text-white sm:text-6xl lg:text-7xl">{t.heroTitle}</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#53655e] dark:text-[#bdcbc4]">{t.heroText}</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/login" className="inline-flex items-center gap-3 bg-[#183b35] px-6 py-3.5 text-sm font-bold text-white transition hover:bg-[#2d5a50]">{t.primary}<ArrowRight className="h-4 w-4" /></Link><button onClick={() => scrollTo("services")} className="border border-[#183b35] bg-transparent px-6 py-3.5 text-sm font-bold text-[#183b35] transition hover:bg-white dark:border-white dark:text-white dark:hover:bg-white/10">{t.secondary}</button></div><div className="mt-10 flex items-center gap-2 text-xs font-semibold text-[#56796c]"><CheckCircle2 className="h-4 w-4 text-[#c28e16]" />{t.official}</div></div><div className="relative"><div className="overflow-hidden border border-[#cbd8d0] bg-white shadow-[0_20px_60px_rgba(24,59,53,0.12)] dark:border-white/10 dark:bg-[#203d35]"><img src="/images/upnm-campus.png" alt="UPNM campus" className="h-[330px] w-full object-cover grayscale-[15%]" /><div className="grid grid-cols-2 border-t border-[#d9e1dc] dark:border-white/10"><div className="p-5"><div className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#718078]">UPNM CMS 2.0</div><div className="mt-1 font-[Poppins] text-lg font-bold">Connected care</div></div><div className="border-l border-[#d9e1dc] p-5 dark:border-white/10"><div className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#718078]">Service status</div><div className="mt-1 flex items-center gap-2 font-[Poppins] text-lg font-bold"><span className="h-2 w-2 rounded-full bg-[#5c956e]" />Online</div></div></div></div><div className="absolute -bottom-5 -left-5 hidden border border-[#d9e1dc] bg-white px-5 py-4 shadow-lg dark:border-white/10 dark:bg-[#203d35] sm:block"><div className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#718078]">{t.motto}</div><div className="mt-1 text-sm font-bold">Clear. Secure. Connected.</div></div></div></div></section>

    <section id="services" className="scroll-mt-20 bg-white py-20 dark:bg-[#10221d] lg:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-10"><div className="max-w-2xl"><div className="text-xs font-bold uppercase tracking-[0.18em] text-[#b18419]">Our services</div><h2 className="mt-4 font-[Poppins] text-3xl font-extrabold tracking-tight sm:text-4xl">{t.servicesTitle}</h2><p className="mt-4 text-base leading-7 text-[#66756e] dark:text-[#bdcbc4]">{t.servicesText}</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{t.services.map(([title, text, Icon]) => <Link href="/login" key={title} className="group border border-[#d9e1dc] bg-[#f6f7f5] p-7 transition hover:-translate-y-2 hover:border-[#7ca08f] dark:border-white/10 dark:bg-[#18352e]"><div className="grid h-12 w-12 place-items-center bg-[#dcebe1] text-[#183b35] dark:bg-[#2b5145] dark:text-white"><Icon className="h-5 w-5" /></div><h3 className="mt-6 font-[Poppins] text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#66756e] dark:text-[#bdcbc4]">{text}</p><span className="mt-6 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-[#56796c] dark:text-[#d6e5dc]">Learn more <ArrowRight className="h-3.5 w-3.5 transition group-hover:translate-x-1" /></span></Link>)}</div></div></section>

    <section id="ecosystem" className="scroll-mt-20 border-y border-[#d9e1dc] bg-[#f6f7f5] py-20 dark:border-white/10 dark:bg-[#18352e] lg:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-10"><div className="mx-auto max-w-2xl text-center"><div className="text-xs font-bold uppercase tracking-[0.18em] text-[#b18419]">Everything Connected</div><h2 className="mt-4 font-[Poppins] text-3xl font-extrabold tracking-tight sm:text-4xl">{t.connectedTitle}</h2><p className="mt-4 text-base leading-7 text-[#66756e] dark:text-[#bdcbc4]">{t.connectedText}</p></div><div className="mt-14 grid gap-0 md:grid-cols-4">{t.connected.map(([number, title, text], i) => <div key={number} className={`group border-[#cbd8d0] py-6 md:px-7 md:py-2 ${i < 3 ? "border-b md:border-b-0 md:border-r" : ""} ${i === 0 ? "md:pl-0" : ""}`}><div className="font-mono text-sm font-bold text-[#b18419]">{number}</div><div className="mt-6 flex items-center gap-2"><span className="h-2 w-2 bg-[#5c956e] transition group-hover:scale-[2]" /><h3 className="font-[Poppins] text-xl font-bold">{title}</h3></div><p className="mt-3 text-sm leading-6 text-[#66756e] dark:text-[#bdcbc4]">{text}</p></div>)}</div></div></section>

    <section id="roles" className="scroll-mt-20 bg-white py-20 dark:bg-[#10221d] lg:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-10"><div className="text-center"><div className="text-xs font-bold uppercase tracking-[0.18em] text-[#b18419]">Precision for every user</div><h2 className="mt-4 font-[Poppins] text-3xl font-extrabold tracking-tight sm:text-4xl">{t.precisionTitle}</h2><p className="mx-auto mt-4 max-w-2xl text-base text-[#66756e] dark:text-[#bdcbc4]">{t.precisionText}</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{t.roles.map(([title, text, Icon]) => <div key={title} className="border border-[#d9e1dc] p-7 transition hover:-translate-y-2 hover:border-[#7ca08f] dark:border-white/10"><div className="flex items-center gap-4"><div className="grid h-11 w-11 place-items-center bg-[#183b35] text-white"><Icon className="h-5 w-5" /></div><h3 className="font-[Poppins] text-lg font-bold">{title}</h3></div><p className="mt-5 text-sm leading-6 text-[#66756e] dark:text-[#bdcbc4]">{text}</p></div>)}</div></div></section>

    <section id="intelligence" className="scroll-mt-20 border-y border-[#d9e1dc] bg-[#e9f0eb] py-20 dark:border-white/10 dark:bg-[#18352e] lg:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-10"><div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-end"><div><div className="text-xs font-bold uppercase tracking-[0.18em] text-[#b18419]">Support at every step</div><h2 className="mt-4 font-[Poppins] text-3xl font-extrabold tracking-tight sm:text-4xl">{t.supportTitle}</h2></div><p className="max-w-xl text-base leading-7 text-[#66756e] dark:text-[#bdcbc4]">{t.supportText}</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{t.support.map(([title, text, Icon]) => <div key={title} className="border border-[#cbd8d0] bg-white p-6 dark:border-white/10 dark:bg-[#203d35]"><Icon className="h-5 w-5 text-[#56796c]" /><h3 className="mt-6 font-[Poppins] text-lg font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#66756e] dark:text-[#bdcbc4]">{text}</p></div>)}</div></div></section>

    <section id="security" className="scroll-mt-20 bg-white py-20 dark:bg-[#10221d] lg:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-10"><div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-end"><div><div className="text-xs font-bold uppercase tracking-[0.18em] text-[#b18419]">Protected by Design</div><h2 className="mt-4 font-[Poppins] text-3xl font-extrabold tracking-tight sm:text-4xl">{t.protectedTitle}</h2></div><p className="max-w-xl text-base leading-7 text-[#66756e] dark:text-[#bdcbc4]">{t.protectedText}</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{t.protected.map(([title, text, Icon]) => <div key={title} className="border border-[#d9e1dc] p-6 dark:border-white/10"><Icon className="h-5 w-5 text-[#183b35] dark:text-[#d6e5dc]" /><h3 className="mt-6 font-[Poppins] text-lg font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#66756e] dark:text-[#bdcbc4]">{text}</p></div>)}</div></div></section>

    <section className="bg-[#183b35] py-14 text-white"><div className="mx-auto flex max-w-7xl flex-col gap-7 px-5 lg:flex-row lg:items-center lg:justify-between lg:px-10"><div><h2 className="font-[Poppins] text-2xl font-bold">Ready to access campus healthcare?</h2><p className="mt-2 text-sm text-[#d6e5dc]">Use your role-based account to continue.</p></div><Link href="/login" className="inline-flex items-center gap-3 self-start bg-[#e5b636] px-6 py-3.5 text-sm font-bold text-[#183b35] hover:bg-[#f1cb62]">{t.access}<ArrowRight className="h-4 w-4" /></Link></div></section>

    <footer className="border-t border-[#d9e1dc] bg-white dark:border-white/10 dark:bg-[#10221d]"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-8 text-xs text-[#718078] sm:flex-row sm:items-center sm:justify-between lg:px-10"><div className="flex items-center gap-2 font-semibold text-[#53655e] dark:text-[#bdcbc4]"><ShieldCheck className="h-4 w-4 text-[#56796c]" />{t.footer}</div><div>UPNM Clinical Management System 2.0 · Secure campus healthcare</div></div></footer>

    <div className="group fixed bottom-5 right-5 z-[60] sm:bottom-8 sm:right-8"><div className={`absolute bottom-[calc(100%+14px)] right-0 w-72 origin-bottom-right border border-[#cbd8d0] bg-white p-4 shadow-[0_16px_40px_rgba(24,59,53,0.18)] transition-all duration-300 dark:border-white/15 dark:bg-[#203d35] ${botOpen ? "translate-y-0 scale-100 opacity-100" : "pointer-events-none translate-y-3 scale-95 opacity-0 group-hover:translate-y-0 group-hover:scale-100 group-hover:opacity-100"}`}><div className="flex items-start gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center bg-[#e9f0eb] text-[#183b35] dark:bg-[#2b5145] dark:text-white"><Bot className="h-5 w-5" /></div><div><div className="font-[Poppins] text-sm font-bold">{t.botGreeting}</div><p className="mt-1 text-xs leading-5 text-[#66756e] dark:text-[#bdcbc4]">{t.botText}</p><Link href="/ai-screener" className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-[#56796c]">{t.botButton}<ChevronRight className="h-3.5 w-3.5" /></Link></div></div><span className="absolute -bottom-2 right-8 h-4 w-4 rotate-45 border-b border-r border-[#cbd8d0] bg-white dark:border-white/15 dark:bg-[#203d35]" /></div><button onClick={() => setBotOpen(!botOpen)} className="group relative grid h-20 w-20 place-items-center overflow-hidden rounded-full border-4 border-white bg-[#e9f0eb] shadow-[0_12px_30px_rgba(24,59,53,0.25)] transition duration-300 hover:scale-110 motion-safe:animate-float dark:border-[#18352e] dark:bg-[#dcebe1]" aria-label={t.botGreeting}><img src="/images/upnm-clinic-bot.jpg" alt="UPNM clinic assistant" className="h-full w-full object-cover object-center transition duration-500 group-hover:scale-125" /><span className="absolute -right-0.5 -top-0.5 h-4 w-4 rounded-full border-2 border-white bg-[#e5b636] motion-safe:animate-ping" /><span className="absolute inset-0 rounded-full ring-2 ring-[#e5b636]/60 motion-safe:animate-pulse" /></button></div>
  </main>;
}
